version: '3.3'
services:
  covid19vaxplorer:
    image: sc-registry.fredhutch.org/covid19vaxplorer:latest
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.covid19vaxplorer.rule=Host(`covid19vaxplorer.fredhutch.org`)"
        - "traefik.http.routers.covid19vaxplorer-secured.rule=Host(`covid19vaxplorer.fredhutch.org`)"
        - "traefik.http.routers.covid19vaxplorer.entrypoints=web,web-secured"
        - "traefik.http.services.covid19vaxplorer.loadbalancer.server.port=5000" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.covid19vaxplorer.tls=true"

networks:
  proxy:
    external: true